-- Star schema for cross-player brawler analytics.
--
-- Grain of brawler_fact: one row per (player_tag, battle_id). Same physical
-- battle observed in different tracked players' logs yields the SAME
-- battle_id (md5 of sorted-min tag + battle_time) and N rows in the fact
-- table — one per participant.
--
-- Loaded by a daily ETL from the OLTP project (see local/db plan.txt).
-- Lives in a separate Supabase project from the OLTP DB; access is gated
-- by Supabase role grants (default service_role only — frontend cannot
-- reach this DB).
--
-- Schema choices vs the sketch in local/db plan.txt:
--   * trophy_dim was dropped — (overall, brawler) trophies are continuous
--     measures, not dimensional attributes. Raw values are kept as measures
--     on the fact; a trophy_band_dim provides the categorical FK for
--     range-style filtering ('winrate in 90k-100k range').
--   * fact grain is explicit at (player_tag, battle_id) so per-player
--     analytics (teammate winrate, brawler picks by player band) work.
--   * placement reuses the OLTP encoding (-1 draw / 0 loss / 1 win for team
--     modes; 1-10 finish position for showdown) so showdown rank queries
--     and draws survive the warehouse round-trip.
--   * date_dim is enriched (dow / iso_week / quarter / is_weekend) to
--     unlock the slicing patterns we want.
--
-- All keys: surrogate smallint identity for dims (low cardinality), int
-- for date_key (YYYYMMDD). battle_id is kept as a natural-key degenerate
-- dim on the fact for traceability back to OLTP.


-- =========================================================================
-- Date dimension
-- =========================================================================
CREATE TABLE public.date_dim (
  date_key      int PRIMARY KEY,        -- YYYYMMDD
  full_date     date NOT NULL UNIQUE,
  year          smallint NOT NULL,
  month         smallint NOT NULL,
  day           smallint NOT NULL,
  day_of_week   smallint NOT NULL,      -- 0=Sun .. 6=Sat (Postgres extract(dow))
  iso_week      smallint NOT NULL,
  quarter       smallint NOT NULL,
  is_weekend    boolean  NOT NULL
);

-- Pre-generate dates for a 7-year window. Cheap (~2.5k rows) and removes
-- the need for the ETL to insert dates on the fly. Extend as needed.
INSERT INTO public.date_dim
  (date_key, full_date, year, month, day, day_of_week, iso_week, quarter, is_weekend)
SELECT
  to_char(d, 'YYYYMMDD')::int,
  d::date,
  EXTRACT(year     FROM d)::smallint,
  EXTRACT(month    FROM d)::smallint,
  EXTRACT(day      FROM d)::smallint,
  EXTRACT(dow      FROM d)::smallint,
  EXTRACT(week     FROM d)::smallint,
  EXTRACT(quarter  FROM d)::smallint,
  EXTRACT(dow FROM d) IN (0, 6)
FROM generate_series('2024-01-01'::date, '2030-12-31'::date, '1 day'::interval) AS d;


-- =========================================================================
-- Brawler dimension
-- =========================================================================
CREATE TABLE public.brawler_dim (
  brawler_key   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brawler_id    int  NOT NULL UNIQUE,   -- natural id from Brawl Stars API
  name          text NOT NULL,
  class         text                    -- one of: Damage Dealer, Tank, Marksman,
                                        -- Artillery, Controller, Assassin, Support
                                        -- NULL for brawlers whose class hasn't
                                        -- been verified by the maintainer.
);

-- Seed: best-effort class mapping reflecting Brawl Stars' current class
-- system. Brawlers released most recently (>= 16000086) are left NULL —
-- update via a follow-up patch once classes are confirmed.
INSERT INTO public.brawler_dim (brawler_id, name, class) VALUES
  (16000000, 'Shelly',         'Damage Dealer'),
  (16000001, 'Colt',            'Damage Dealer'),
  (16000002, 'Bull',            'Tank'),
  (16000003, 'Brock',           'Marksman'),
  (16000004, 'Rico',            'Damage Dealer'),
  (16000005, 'Spike',           'Damage Dealer'),
  (16000006, 'Barley',          'Artillery'),
  (16000007, 'Jessie',          'Damage Dealer'),
  (16000008, 'Nita',            'Damage Dealer'),
  (16000009, 'Dynamike',        'Artillery'),
  (16000010, 'El Primo',        'Tank'),
  (16000011, 'Mortis',          'Assassin'),
  (16000012, 'Crow',            'Assassin'),
  (16000013, 'Poco',            'Support'),
  (16000014, 'Bo',              'Controller'),
  (16000015, 'Piper',           'Marksman'),
  (16000016, 'Pam',             'Support'),
  (16000017, 'Tara',            'Controller'),
  (16000018, 'Darryl',          'Tank'),
  (16000019, 'Penny',           'Controller'),
  (16000020, 'Frank',           'Tank'),
  (16000021, 'Gene',            'Controller'),
  (16000022, 'Tick',            'Artillery'),
  (16000023, 'Leon',            'Assassin'),
  (16000024, 'Rosa',            'Tank'),
  (16000025, 'Carl',            'Damage Dealer'),
  (16000026, 'Bibi',            'Tank'),
  (16000027, '8-Bit',           'Damage Dealer'),
  (16000028, 'Sandy',           'Controller'),
  (16000029, 'Bea',             'Damage Dealer'),
  (16000030, 'Emz',             'Controller'),
  (16000031, 'Mr. P',           'Controller'),
  (16000032, 'Max',             'Support'),
  (16000034, 'Jacky',           'Tank'),
  (16000035, 'Gale',            'Controller'),
  (16000036, 'Nani',            'Damage Dealer'),
  (16000037, 'Sprout',          'Controller'),
  (16000038, 'Surge',           'Damage Dealer'),
  (16000039, 'Colette',         'Damage Dealer'),
  (16000040, 'Amber',           'Damage Dealer'),
  (16000041, 'Lou',             'Controller'),
  (16000042, 'Byron',           'Support'),
  (16000043, 'Edgar',           'Assassin'),
  (16000044, 'Ruffs',           'Support'),
  (16000045, 'Stu',             'Assassin'),
  (16000046, 'Belle',           'Marksman'),
  (16000047, 'Squeak',          'Controller'),
  (16000048, 'Grom',            'Artillery'),
  (16000049, 'Buzz',            'Tank'),
  (16000050, 'Griff',           'Damage Dealer'),
  (16000051, 'Ash',             'Tank'),
  (16000052, 'Meg',             'Tank'),
  (16000053, 'Lola',            'Damage Dealer'),
  (16000054, 'Fang',            'Assassin'),
  (16000056, 'Eve',             'Controller'),
  (16000057, 'Janet',           'Controller'),
  (16000058, 'Bonnie',          'Marksman'),
  (16000059, 'Otis',            'Damage Dealer'),
  (16000060, 'Sam',             'Tank'),
  (16000061, 'Gus',             'Support'),
  (16000062, 'Buster',          'Tank'),
  (16000063, 'Chester',         'Damage Dealer'),
  (16000064, 'Gray',            'Assassin'),
  (16000065, 'Mandy',           'Marksman'),
  (16000066, 'R-T',             'Damage Dealer'),
  (16000067, 'Willow',          'Artillery'),
  (16000068, 'Maisie',          'Marksman'),
  (16000069, 'Hank',            'Tank'),
  (16000070, 'Cordelius',       'Assassin'),
  (16000071, 'Doug',            'Support'),
  (16000072, 'Pearl',           'Damage Dealer'),
  (16000073, 'Chuck',           'Controller'),
  (16000074, 'Charlie',         'Controller'),
  (16000075, 'Mico',            'Assassin'),
  (16000076, 'Kit',             'Assassin'),
  (16000077, 'Larry & Lawrie',  'Controller'),
  (16000078, 'Melodie',         'Assassin'),
  (16000079, 'Angelo',          'Marksman'),
  (16000080, 'Draco',           'Tank'),
  (16000081, 'Lily',            'Assassin'),
  (16000082, 'Berry',           'Support'),
  (16000083, 'Clancy',          'Damage Dealer'),
  (16000084, 'Moe',             'Damage Dealer'),
  (16000085, 'Kenji',           'Assassin'),
  -- Verify and patch class for the entries below before relying on
  -- class-grouped analytics.
  (16000086, 'Shade',           'Assassin'),
  (16000087, 'Juju',            'Artillery'),
  (16000089, 'Meeple',          'Controller'),
  (16000090, 'Ollie',           'Tank'),
  (16000091, 'Lumi',            'Damage Dealer'),
  (16000092, 'Finx',            'Controller'),
  (16000093, 'Jae-Yong',        'Support'),
  (16000094, 'Kaze',            'Damage Dealer'),
  (16000095, 'Alli',            'Assassin'),
  (16000096, 'Trunk',           'Tank'),
  (16000097, 'Mina',            'Assassin'),
  (16000098, 'Ziggy',           'Artillery'),
  (16000099, 'Pierce',          'Marksman'),
  (16000100, 'Gigi',            'Assassin'),
  (16000101, 'Glowy',           'Support'),
  (16000102, 'Sirius',          'Artillery'),
  (16000103, 'Najia',           'Marksman'),
  (16000104, 'Damian',          'Tank'),
  (16000105, 'Star Nova',       'Assassin'),
  (16000106, 'Bolt',            'Tank');


-- =========================================================================
-- Battle dimension (mode + map combos)
-- =========================================================================
CREATE TABLE public.battle_dim (
  battle_dim_key smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mode           text NOT NULL,
  mode_id        smallint,              -- internal mapping from brawl-data-service/utils/modeMap.ts
  map            text NOT NULL,
  UNIQUE (mode, map)
);
-- No seed. Populated by ETL on first observation of each (mode, map) combo.


-- =========================================================================
-- Trophy band dimension
-- =========================================================================
CREATE TABLE public.trophy_band_dim (
  trophy_band_key smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  band_min        int  NOT NULL,
  band_max        int  NOT NULL,         -- inclusive upper bound
  label           text NOT NULL UNIQUE,
  CHECK (band_min <= band_max)
);

-- 10k-wide bands across the realistic trophy range, plus an overflow band
-- for any future inflation past 150k.
INSERT INTO public.trophy_band_dim (band_min, band_max, label) VALUES
  (0,       9999,        '0-10k'),
  (10000,   19999,       '10k-20k'),
  (20000,   29999,       '20k-30k'),
  (30000,   39999,       '30k-40k'),
  (40000,   49999,       '40k-50k'),
  (50000,   59999,       '50k-60k'),
  (60000,   69999,       '60k-70k'),
  (70000,   79999,       '70k-80k'),
  (80000,   89999,       '80k-90k'),
  (90000,   99999,       '90k-100k'),
  (100000,  109999,      '100k-110k'),
  (110000,  119999,      '110k-120k'),
  (120000,  129999,      '120k-130k'),
  (130000,  139999,      '130k-140k'),
  (140000,  2147483647,  '140k+');


-- =========================================================================
-- Brawler trophy band dimension (per-brawler trophies)
-- =========================================================================
-- Separate from trophy_band_dim above: that one bins a player's TOTAL
-- trophies (sum across all brawlers); this one bins the trophies on a
-- single brawler — a different distribution with a much lower ceiling
-- (Brawl Stars caps per-brawler progression around 1500 with diminishing
-- meta-relevance past ~2000; high outliers still happen).
--
-- Bands widen as resolution stops mattering:
--   0-1000:    500-wide  (early progression, group coarsely)
--   1000-2000: 250-wide  (middle range — most active players sit here)
--   2000-4000: 100-wide  (high-trophy meta range — finest resolution)
--   4000+:     overflow
CREATE TABLE public.brawler_trophy_band_dim (
  brawler_trophy_band_key smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  band_min                int  NOT NULL,
  band_max                int  NOT NULL,    -- inclusive upper bound
  label                   text NOT NULL UNIQUE,
  CHECK (band_min <= band_max)
);

INSERT INTO public.brawler_trophy_band_dim (band_min, band_max, label) VALUES
  (0,    499,         '0-500'),
  (500,  999,         '500-1000'),
  (1000, 1249,        '1000-1250'),
  (1250, 1499,        '1250-1500'),
  (1500, 1749,        '1500-1750'),
  (1750, 1999,        '1750-2000'),
  (2000, 2099,        '2000-2100'),
  (2100, 2199,        '2100-2200'),
  (2200, 2299,        '2200-2300'),
  (2300, 2399,        '2300-2400'),
  (2400, 2499,        '2400-2500'),
  (2500, 2599,        '2500-2600'),
  (2600, 2699,        '2600-2700'),
  (2700, 2799,        '2700-2800'),
  (2800, 2899,        '2800-2900'),
  (2900, 2999,        '2900-3000'),
  (3000, 3099,        '3000-3100'),
  (3100, 3199,        '3100-3200'),
  (3200, 3299,        '3200-3300'),
  (3300, 3399,        '3300-3400'),
  (3400, 3499,        '3400-3500'),
  (3500, 3599,        '3500-3600'),
  (3600, 3699,        '3600-3700'),
  (3700, 3799,        '3700-3800'),
  (3800, 3899,        '3800-3900'),
  (3900, 3999,        '3900-4000'),
  (4000, 2147483647,  '4000+');


-- =========================================================================
-- Fact table
-- =========================================================================
CREATE TABLE public.brawler_fact (
  -- Composite grain — same physical battle has one row per participant.
  player_tag        text NOT NULL,
  battle_id         text NOT NULL,       -- degenerate dim (md5 from OLTP)

  -- Dimensional FKs.
  date_key          int      NOT NULL REFERENCES public.date_dim(date_key),
  brawler_key       smallint NOT NULL REFERENCES public.brawler_dim(brawler_key),
  battle_dim_key    smallint NOT NULL REFERENCES public.battle_dim(battle_dim_key),
  trophy_band_key   smallint          REFERENCES public.trophy_band_dim(trophy_band_key),
    -- NULL when overall_trophies is unknown (non-targeted participant —
    -- the OLTP only knows total trophies for the queried player).
  brawler_trophy_band_key smallint NOT NULL
    REFERENCES public.brawler_trophy_band_dim(brawler_trophy_band_key),
    -- Always known: brawler_trophies is required for every participant in
    -- the OLTP brawler_trophies_store (it's returned by the API for all
    -- players in the battle).

  -- Natural timestamp retained for hour-of-day slicing without a time dim.
  battle_time       timestamptz NOT NULL,

  -- Measures.
  placement         smallint,            -- -1 draw / 0 loss / 1 win / 1..10 showdown rank / NULL unknown
  overall_trophies  int,                 -- player's total trophies after battle (queried player only)
  brawler_trophies  int,                 -- per-brawler trophies after battle
  trophy_change     int NOT NULL DEFAULT 0,

  PRIMARY KEY (player_tag, battle_id)
);

-- Per-FK indexes for star-shaped filter + join queries.
CREATE INDEX brawler_fact_brawler_key_idx      ON public.brawler_fact (brawler_key);
CREATE INDEX brawler_fact_battle_dim_key_idx   ON public.brawler_fact (battle_dim_key);
CREATE INDEX brawler_fact_trophy_band_key_idx  ON public.brawler_fact (trophy_band_key);
CREATE INDEX brawler_fact_brawler_trophy_band_key_idx
  ON public.brawler_fact (brawler_trophy_band_key);
CREATE INDEX brawler_fact_date_key_idx         ON public.brawler_fact (date_key);
CREATE INDEX brawler_fact_battle_id_idx        ON public.brawler_fact (battle_id);

-- BRIN on battle_time: append-mostly time series, BRIN gives near-zero
-- maintenance cost and tight summarization for time-range scans.
CREATE INDEX brawler_fact_battle_time_brin_idx
  ON public.brawler_fact USING brin (battle_time);
